### ISSUE TITLE
The pre-training weights of Dual-Encoder Baseline (with TSF-B/L)

### ISSUE THREAD

**Issue by daiguangzhao** [facebookresearch/LaViLa#21] opened 2023-07-18 03:28 UTC
Thanks to the author for his contribution to the ego community. It's cool work! Would you mind releasing the pre-training weights of the Dual-Encoder Baseline (with TSF-B/L)?

**Comment by zhaoyue-zephyrus** [comment] 2023-07-18 03:38
Duplicate of #20 .

**Closed by zhaoyue-zephyrus** 2023-07-18 03:38 UTC
